name = "AssemblyCalculus"
uuid = "6644f8a4-7ba1-11ec-3c70-090e16a6069e"
authors = ["DJ Passey <djpasseyjr@gmail.com>"]
version = "0.0.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
